name: CI Build Linux 🐧| Windows 🖥️

on: [ push, pull_request, workflow_dispatch ]

jobs:
  # The CMake configure and build commands are platform-agnostic and should work equally
  # well on Windows or Mac.  You can convert this to a matrix build if you need
  # cross-platform coverage.
  # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  build_all:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            artifact-name: ubuntu-build

          - os: windows-latest
            artifact-name: windows-build

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build Debug
        run: cargo build

      - name: Build Release
        run: cargo build --release